pipeline {
    agent {
        docker { image 'node:16.13.1-alpine' }
    }
    stages {
        def commit_id
        stage('Preparation') {
            checkout scm
            sh "git rev-parse --short HEAD > .git/commit-id"
            commit_id = readFile('.git/commit-id').trim()
        }
        stage('Test') {
            steps {
                sh 'node --version'
                sh 'echo "Commit ID: ${commit_id}"'
            }
        }
    }
}