// pipeline {
//     agent any
//     stages {
//         // def commit_id
//         // stage('Preparation') {
//         //     checkout scm
//         //     sh "git rev-parse --short HEAD > .git/commit-id"
//         //     commit_id = readFile('.git/commit-id').trim()
//         // }
//         stage('Test') {
//             docker { 
//                 image 'node:16.13.1-alpine'
//                 reuseNode true
//             }
//             steps {
//                 sh 'node --version'
//                 // sh 'echo "Commit ID: ${commit_id}"'
//             }
//         }
//     }
// }

node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('docker build/push') {            
     docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {
       def app = docker.build("0908887875/docker-nodejs-demo:${commit_id}", '.').push()
     }                                     
   }                                       
}  